# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_title_count', models.IntegerField(default=0)),
                ('happy_text_count', models.IntegerField(default=0)),
                ('sad_title_count', models.IntegerField(default=0)),
                ('sad_text_count', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_check.Stock')),
            ],
        ),
    ]
