# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0002_vibe'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibe',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
