# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0003_vibe_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vibe',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_check.Company'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
