# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0004_auto_20160311_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='lon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
