# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0006_auto_20160311_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='lon',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
