# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0008_auto_20160311_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='lon',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
