# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0009_auto_20160311_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibe',
            name='blob_text_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vibe',
            name='blog_title_score',
            field=models.IntegerField(default=0),
        ),
    ]
