# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0010_auto_20160314_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vibe',
            old_name='blog_title_score',
            new_name='blob_title_score',
        ),
    ]
