# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_check', '0011_auto_20160314_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibe',
            name='blob_text_score',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='vibe',
            name='blob_title_score',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=11),
        ),
    ]
